#
#  Settings for using a mySQL database
###
MySQL:
  Enabled: false
  Username: UserName
  Password: UserPassword
  Database-Name: DataBaseName
  Server:
      SSL: false
      Port: 3306
      Address: localhost

#
#  Settings for Factions compatability
#  
#  Enabled: (true/false) Is the support enabled?
#  Tokens-To-Power: (any number) How much faction power is 1 token worth?
#
###
Factions:
  Enabled: false
  Tokens-To-Power: 2

#
#  Settings for CombatLogX compatability
#  
#  Enabled: (true/false) Is the support enabled?
#  Block-Tokens: (true/false) Are the token commands blocked in combat?
#  ^ This option kinda disables the use of hooking into combat log but ¯\_(ツ)_/¯ more options is better?
#
###
CombatLogX:
  Enabled: false
  Block-Tokens: true